Update requirements.txt
I think 'pandas_flavor' is what is needed to be pip installed instead of 'pandas-flavor'. I got following error after installing rdkit and scikit-learn as instructed:

Input lines:
'''
from descriptastorus.descriptors.DescriptorGenerator import MakeGenerator
generator = MakeGenerator(("RDKit2D",))
for name, numpy_type in generator.GetColumns():
  print("name: {} data type: {}".format(name, numpy_type))
'''

Error:
'''
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-539f82d21e77> in <module>
----> 1 from descriptastorus.descriptors.DescriptorGenerator import MakeGenerator
      2 generator = MakeGenerator(("RDKit2D",))
      3 for name, numpy_type in generator.GetColumns():
      4   print("name: {} data type: {}".format(name, numpy_type))

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/descriptastorus/descriptors/__init__.py in <module>
      1 import logging
----> 2 from .DescriptorGenerator import *
      3 from .rdDescriptors import *
      4 from .rdNormalizedDescriptors import *
      5 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/descriptastorus/descriptors/DescriptorGenerator.py in <module>
     33 import logging, numpy, sys
     34 import pandas as pd
---> 35 import pandas_flavor as pf
     36 
     37 # set to 0 to disable caching

ModuleNotFoundError: No module named 'pandas_flavor'
'''